name: webview_app
description: "A simple Flutter WebView App with file picker, storage access, and offline support."
publish_to: 'none'  # Remove this line if you plan to publish the package to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # WebView plugin
  webview_flutter: ^4.0.0

  # File picker
  file_picker: ^5.2.1

  # URL launcher
  url_launcher: ^6.0.20

  # Permission handler for storage
  permission_handler: ^10.0.0

  # Path provider to access the file system
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/404.html  # Ensure this file exists in the `assets` directory
