name: webview_app
description: "A simple Flutter WebView App with Ads and Offline Support."
publish_to: 'none'  # Hapus baris ini jika ingin mempublikasikan ke pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.3  
  webview_flutter: ^4.7.0
  webview_flutter_android: ^3.10.0
  webview_flutter_wkwebview: ^3.10.0
  connectivity_plus: ^6.0.3
  flutter_native_splash: ^2.3.11
  permission_handler: ^11.0.1  # Gunakan versi terbaru
  flutter_file_dialog: ^3.0.0
  flutter_downloader: ^1.10.0
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/404.html  # Pastikan file ini ada di folder `assets`
