name: webview_app
description: "A simple Flutter WebView App with Ads and Offline Support."
publish_to: 'none'  # Hapus ini jika Anda ingin mempublikasikan ke pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.3

  # WebView dan plugin pendukung
  webview_flutter: ^4.7.0
  webview_flutter_android: ^3.10.0
  webview_flutter_wkwebview: ^3.10.0

  # Cek koneksi internet
  connectivity_plus: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/404.html  # Pastikan file ini ada di folder `assets`
